// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameArticle = "article"

// Article mapped from table <article>
type Article struct {
	ID         uint           `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title      string         `gorm:"column:title" json:"title"`
	Content    string         `gorm:"column:content" json:"content"`
	CreateTime time.Time      `gorm:"column:create_time" json:"create_time"`
	UpdateTime time.Time      `gorm:"column:update_time" json:"update_time"`
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time" json:"delete_time"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
